[package]
name = "new_lang_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabled = { version = "0.12.0"}

[dev-dependencies]
pretty_assertions = "1.3.0"